#!/usr/bin/python

# this function essentially tries to scan through files in a directory, 
# read and compare - and if there's a change creates a new file with new name
# this attempt failed but it can be built upon

def place():
	import os
	place = os.system('pwd'(os.renames("ostry1.py","new name here")))
	print "The dir is: %s" %os.listdir(os.getcwd())
	return place

# it needs to list the directory's contents first
# then compare output and creates new one if no similarity exist

place()
